##===- projects/CPI/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../..

#
# List all of the subdirectories that we will compile.
#
DIRS=SFReach Search Invariant CFG Dependence ID LiveAnalysis Utility

include $(LEVEL)/Makefile.common
