##===- projects/CPI/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../..

#
# List all of the subdirectories that we will compile.
#
DIRS=InterProcDep MemRange InvArray

include $(LEVEL)/Makefile.common
