##===- projects/CPI/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../..

#
# List all of the subdirectories that we will compile.
#
DIRS=CI-Redundancy CL-Redundancy FFR-Redundancy SysC-Redundancy

include $(LEVEL)/Makefile.common
